### PR TITLE
Adding libtmglib.

### LINKED ISSUE #48: Add a libtmglib output just like libblas
@hhslepicka if you can help with this, we can fix this faster.

### PR DESCRIPTION
**Pull request by hhslepicka**
Closes #48 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
@isuruf this seems good for a review... Thank you for the guidelines on how to do it.

I added tests for the outputs and later I realized that they are likely being covered by `blas`.
I can revert https://github.com/conda-forge/lapack-feedstock/pull/49/commits/715f6b337c8580e68e5d58e6076a61546de2e3b4 if that's a problem.

**Comment by hhslepicka** [comment]
Duplicated tests were reverted via https://github.com/conda-forge/lapack-feedstock/pull/49/commits/3561e257a8c8384da1e1ed46efdfd751a3b8ad03

**Comment by hhslepicka** [comment]
@isuruf @jakirkham I am not sure why osx_arm64 is no longer recognizing the gfortran compiler.
The latest feedstock build worked but for PRs it is failing.
It seems unrelated to this change. I will try to find the difference between them but I would appreciate if you could take a look.

**Comment by hhslepicka** [comment]
@conda-forge-admin, please restart CI

**Comment by h-vetinari** [comment]
Bit further up in the log:
```
-- The Fortran compiler identification is GNU 11.0.0
arm64-apple-darwin20.0.0-gfortran: fatal error: cannot execute ‘cc1’: execvp: No such file or directory
compilation terminated.
```

Not sure where cc1 is supposed to come from either though.

**Comment by hhslepicka** [comment]
@h-vetinari the cc1 missing is due to a known issue with gfortran under OS X.
The issue and workaround can be found here: https://github.com/conda-forge/gfortran_osx-64-feedstock/issues/11#issuecomment-725890478

I can try to add that to get rid of the warning but my concern is more with the seg fault happening during compilation.

**Pull request merged**
