### PR TITLE
Update to 3.11

### PR DESCRIPTION
**Pull request by jschueller**
Closes #62

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
ready to go @conda-forge/lapack

**Comment by h-vetinari** [comment]
We waited a _really_ long time to get #51 merged, because we basically want all BLAS/LAPACK implementations to support the same LAPACK feature level, and MKL is generally far behind.

Also, we haven't enabled 3.10 in the blas-metapackage [yet](https://github.com/conda-forge/blas-feedstock/pull/96), which is IMO the next reasonable step...

**Comment by isuruf** [comment]
Merging this as is will make the netlib variant higher priority. Here's what we can do,
1. Merge this PR with target to `conda-forge/label/lapack`
2. Build blas-metapackage without MKL and drop windows for 3.11
3. Move these pacakges to main label

To be clear this only gives the ability of downstream feedstocks to target new APIs in 3.10 and 3.11, but not any performance benefits as we enable latest versions of openblas, MKL, etc with 3.9.

**Comment by jschueller** [comment]
ok, in this case it can wait, I let you decide

**Comment by h-vetinari** [comment]
The Intel team helping us with repackaging MKL has [asked](https://github.com/conda-forge/intel_repack-feedstock/issues/44#issuecomment-2010997019) to be able to test blas metapackage against LAPACK 3.11, as there are failures with 3.10.1.

The `main` branch here already points to a separate label:
https://github.com/conda-forge/lapack-feedstock/blob/f675059b113d06f34332c359cc18f505554724d9/recipe/conda_build_config.yaml#L1-L2

so we can safely merge this PR. Then it becomes easy to test the various implementations against 3.11 on the blas feedstock, without yet making this generally available.

PS. Thanks a lot for the PR!

**Pull request merged**
