### PR TITLE
Build for 3.10.1

### PR DESCRIPTION
**Pull request by h-vetinari**
Upstream unexpectedly released 3.9.1 (unexpected because 3.10 was planned for end of February), let's try building it.

Edit: actually, the tag was removed again and replaced with `3.9.1-pre`.
Edit 2: final 3.9.1 tag has been republished

Closes #54
Closes #58 
Closes #59

### CODE REVIEW

**Comment by h-vetinari** [comment]
Opened an issue upstream for the one remaining windows failure: https://github.com/Reference-LAPACK/lapack/issues/548

**Comment by h-vetinari** [comment]
https://github.com/conda-forge/lapack-feedstock/pull/51/commits/3835a4de851f90555b5a6ce6bdd3e6d66b57e675 was an upstream ask for debugging; let's not merge this as is just yet - ideally we can figure out Reference-LAPACK/lapack#548 and backport the patch.

**Comment by h-vetinari** [comment]
Upstream issue has been fixed, patch backport has been cleaned up, and this is ready for review @conda-forge/lapack.

I dared to add myself to the maintainers, since I'm now already involved in most of the CF blas-stack, but happy to take out that last commit if desired.

**Comment by h-vetinari** [comment]
Drone just timed out (and is not susceptible to close/open) 😒

**Comment by h-vetinari** [comment]
drone being difficult...

```
fatal: unable to access 'https://github.com/conda-forge/lapack-feedstock.git/': Failed to connect to github.com port 443: Operation timed out
```

**Comment by h-vetinari** [comment]
@isuruf 
What do you think about lapack 3.9.1 - this would be ready? Should mainly be bugfixes, all the real features (AFAICT) were merged only for the upcoming 3.10.0.

**Comment by isuruf** [comment]
Does openblas, mkl suport lapack 3.9.1? If not, we can't merge this.

**Comment by h-vetinari** [comment]
The way I understood @martin-frbg, openblas is already [beyond](https://github.com/xianyi/OpenBLAS/pull/3206#issuecomment-830126173) 3.9.1 with its internal lapack version.

For MKL, I have 3 thoughts:
* 3.9.1. is a patch release, there shouldn't be anything new in there to be compatible with
* the actual mechanism determining which version is pulled in is in the blas-feedstock anyway, right?
* for 3.9.0, MKL was first skipped and then added [later](https://github.com/conda-forge/blas-feedstock/pull/55), which would clearly be possible here as well...?

In any case, I opened https://github.com/conda-forge/intel_repack-feedstock/issues/24 "upstream".

**Comment by h-vetinari** [comment]
Ping @isuruf 

>   * for 3.9.0, MKL was first skipped and then added [later](https://github.com/conda-forge/blas-feedstock/pull/55), which would clearly be possible here as well...?

**Comment by martin-frbg** [comment]
Regarding openblas, the sudden release of 3.10.0 took me by surprise - while I have kept cherry-picking from their development branch, I would still need to integrate at least their patches for CBLAS and LAPACKE compatibility with Fortran "hidden" character length arguments. (And there is a ton of non-code differences not yet merged: some improved comments on the algorithms used in a few files, and above all the removal of all dates and version numbers from all of their source files)

**Comment by h-vetinari** [comment]
Thanks @martin-frbg - 3.10.0 will take a while I guess (so no rush for openblas) - however, this PR is just about 3.9.1. 🙃

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@isuruf, I'm trying to backport https://github.com/Reference-LAPACK/lapack/pull/597, but it does not apply easily to 3.9.0. I can try to hack something together, but I'd really rather merge this and just delay the MKL 3.9.1 builds (as you [did](https://github.com/conda-forge/blas-feedstock/pull/52) for 3.9.0).

**Comment by martin-frbg** [comment]
IIRC, 3.9.0 did not take any special measures to ensure some tests are run single-threaded only. So the code you want to patch may not actually be there yet.

**Comment by h-vetinari** [comment]
> 
> 
> IIRC, 3.9.0 did not take any special measures to ensure some tests are run single-threaded only. So the code you want to patch may not actually be there yet.

The issue that Isuru is concerned about - to my understanding - is less about the single threading and more the compatibility with lapack 3.9.1 across the different versions that conda-forge supports. Openblas 0.3.17 obviously does support 3.9.1 already, but MKL doesn't [yet](https://github.com/conda-forge/intel_repack-feedstock/issues/24#issuecomment-851802338).

For 3.9.0, netlib/openblas were published before MKL (from the POV of conda-forge), but since I haven't heard back I'm not sure what other concerns Isuru might have.

**Comment by h-vetinari** [comment]
Took me a while to pick up this PR after it sat in an echo chamber for so long, but it's green on first push! 🙃 

In any case, MKL [supports](https://github.com/conda-forge/intel_repack-feedstock/issues/26#issuecomment-1264090693) LAPACK 3.10.1 since 2022.2, so does [openblas](https://github.com/xianyi/OpenBLAS/pull/3609) since 0.3.21, and blis [thinks](https://github.com/flame/blis/issues/699) they're compatible too, or will at least endeavour to fix issues as they arise.

PTAL @conda-forge/lapack

**Comment by isuruf** [comment]
Have you checked that https://github.com/conda-forge/blas-feedstock/pull/96 works by building this locally?

**Comment by h-vetinari** [comment]
> Have you checked that [conda-forge/blas-feedstock#96](https://github.com/conda-forge/blas-feedstock/pull/96) works by building this locally?

Given that all implementations claim compatibility, I'm planning to figure this out on the blas feedstock (and would follow up with the respective implementations if they're failing tests or whatever). I don't have the hardware to test this across platforms in advance, and I don't think that's a reasonable bar in this situation?

**Comment by isuruf** [comment]
Let's push to a `rc` label

**Comment by h-vetinari** [comment]
> Let's push to a `rc` label

Done 👍

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
