### PR TITLE
ensure versions for output 'blas' don't overlap

### PR DESCRIPTION
**Pull request by h-vetinari**
Sister PR for fixing the same issue as https://github.com/conda-forge/blas-feedstock/pull/60.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by h-vetinari** [comment]
As stated [here](https://github.com/conda-forge/blas-feedstock/pull/63#issuecomment-753486686) for blas, I'd be willing to become a maintainer for this feedstock.

**Comment by h-vetinari** [comment]
@isuruf, WDYT about this one?

**Comment by isuruf** [comment]
Looks good to me. I'll merge it the next time that there's an update

**Pull request merged**
