### PR TITLE
Split packages

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/lapack, do you mind if I push the artifacts built here to the `conda-forge/label/dev` channel?

**Comment by isuruf** [comment]
Merging this to a separate branch and label

**Comment by hmaarrfk** [comment]
awesome work!!!!! This upgrade will probably go a long way toward getting it to work with the new compilers!!!

**Comment by mariusvniekerk** [comment]
@isuruf you may want to edit this PR to change the base to split, so that you can merge it?

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
